version: "3.9"

services:
  # this service should use the web image after you build it
  web:
    build:
      context: ./welcome-app
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    restart: always
