name: Docker-Compose-Deployment

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu/app/docker-compose-ci-cd/
          remote_host: "${{ secrets.EC2_REMOTE_HOST }}"
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Docker Compose Up
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "docker-compose.yml"
          up-flags: "--force-recreate -d --build"
          down-flags: ""
